### ISSUE TITLE
PVR crash on windows 64

### ISSUE THREAD

**Issue by jejmule** [rbuehlma/pvr.teleboy#16]
Hello,
I am trying to use pvr.teleboy on last Kodi nightlies : KodiSetup-20181122-8dfbf796-master-x64.exe
I install the teleboy pvr client and setup my user information.
I restart Kodi and I have the folllowing errors in the log : 

ERROR: AddOnLog: Teleboy PVR Client: No user settings found.
ERROR: AddOnLog: Teleboy PVR Client: Login failed
NOTICE: PVR Manager: Starting
ERROR: CCurlFile::Open failed with code 404 for http://tv.api.teleboy.ch/users//recordings/planned?desc=1&expand=flags,logos&limit=100&skip=0&sort=date:
ERROR: AddOnLog: Teleboy PVR Client: Error getting recordings of type planned.
ERROR: CCurlFile::Open failed with code 404 for http://tv.api.teleboy.ch/users//recordings/ready?desc=1&expand=flags,logos&limit=100&skip=0&sort=date:
ERROR: AddOnLog: Teleboy PVR Client: Error getting recordings of type ready.

I am located in Switzerland with a working free user account.
I am planning to use Kodi on raspberry  and I want to make sure teleboy is working before.

Thanks for your help

**Comment by rbuehlma** [comment]
> ERROR: AddOnLog: Teleboy PVR Client: No user settings found.

Could you verify that your user information is actually set in the addon settings? It already happend to me, that I missed to push the ok button. Or my be the credentials are wrong?

**Comment by jejmule** [comment]
I have corrected my user name, I was using "myusername" instead of "myusername@gmail.com"
I cannot start teleboy the "run" button is grayed, I have the following error in the log, I do not know if it is related or not : 

ERROR: XFILE::CDirectory::GetDirectory - Error getting
ERROR: Previous line repeats 2 times.

**Comment by rbuehlma** [comment]
There is no need to "Run" it. Just enable it. Afterwards, you should be able to use the "TV" item in the main menu.

**Comment by jejmule** [comment]
It works, thanks :)

**Comment by rbuehlma** [comment]
Perfect. Closing the issue
