### ISSUE TITLE
Set correct genres

### ISSUE THREAD

**Issue by quthla** [rbuehlma/pvr.teleboy#25]
Currently the [type](https://github.com/rbuehlma/pvr.teleboy/blob/Matrix/src/TeleBoy.cpp#L405) is used as genre but the actual genre should be translated with genre_id.

You can get a list of all available genres [here](https://tv.api.teleboy.ch/epg/genres)

**Comment by rbuehlma** [comment]
Should be fixed with 18.0.25.
Thanks for the input.

**Comment by quthla** [comment]
Matrix addon repo still has 19.2.0 instead of [19.2.2](https://github.com/rbuehlma/pvr.teleboy/blob/Matrix/pvr.teleboy/addon.xml.in#L3) when checking with Kodi Nightly 20191104-a4dfad67-master-x64.

Is there anything you need to do in order to get the current version into the Matrix repo?

**Comment by rbuehlma** [comment]
I now tagged the current version. It should now get into the Matrix repository. Please note that I currently do not use any Matrix version of Kodi and do not know how the addon performs there.
