### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by Hir0-84** [rbuehlma/pvr.teleboy#28]
Dear developer,

the pvr client fails to connect showing the error:

ERROR: AddOnLog: Teleboy PVR Client: Login failed.

User and password are correct. Often it fails but not always.
Even when it is able to connect the list of favorite channels does not seems to be the most up-to-date.

Do you experience the same issue? 

I am running on Kodi 18.4 on android tv (teleboy version 18.0.25)  

Best regards,

**Comment by rbuehlma** [comment]
This should be fixed in 18.1.0 by persisting the session cookie. After the update, you might need to first login in the browser and open your account page to make sure that cloudflare is forwarding the requests. Then the addon should be able to login and persist the session.

**Comment by Hir0-84** [comment]
Hi rbuehlma,

when you will able to push the new version on Kodi repository for Android? How can I check the current version number available here on git? For Leia I can see only the version 18.0.24.

**Comment by rbuehlma** [comment]
The repository is updated automatically. I would expect that this happens within a few hours or maybe 1-2 days but I'm not sure whether it is the same for the android repository.

**Comment by Hir0-84** [comment]
Ok thank you very much!

**Comment by Kaischi1981** [comment]
> Sehr geehrter Entwickler,
> 
> Der PvR-Client kann keine Verbindung herstellen und zeigt den Fehler an:
> 
> FEHLER: AddOnLog: Teleboy PVR Client: Anmeldung fehlgeschlagen.
> 
> Benutzer und Passwort sind korrekt. Oft scheitert es aber nicht immer.
> Auch wenn es in der Lage ist, die Liste der Lieblingssender zu verbinden, scheint dies nicht die aktuellste zu sein.
> 
> Haben Sie das gleiche Problem?
> 
> Ich laufe auf Kodi 18.4 auf Android TV (Teleboy Version 18.0.25)
> 
> Freundliche Grüße,


Hallo,ich habe mal eine Frage?Wird der freue Account für den PVR Client wieder frei geschaltet, seitdem die neue Version draußen ist funktioniert die Teleboy Version leider nicht mehr.Sehr schade das die free Version nicht mehr läuft.

**Comment by Hir0-84** [comment]
Sorry I do not speak German. I get again the same error message. When I connect to the Teleboy webpage the list of channel is empty

**Comment by rbuehlma** [comment]
Please open a new ticket and provide a complete debug log. There is not much I can do without any information
