### ISSUE TITLE
get.Recodrings via json/rpc only have 2 genres

### ISSUE THREAD

**Issue by tuxfuxch** [rbuehlma/pvr.teleboy#42]
Hi,

if i get the recordings over JSON-RPC (with PVR.GetRecordings) the only genres i get are 
0: "Andere"
1: "Unbekannt"
for every sinlge entry. in the GUI i can see in the programm-overview that it is implemented and seem correct.

i suppose it is filled wrongly into the DB. can that be corrected? Would be nice!

I love this plugin!
Happy new year!
tuxfuxch

**Comment by rbuehlma** [comment]
The genre for recordings was just not implemented. I now did this in version 18.2.1/19.4.1
As soon as the update is available for your platform, this should be fixed.

**Comment by tuxfuxch** [comment]
i upgraded and it works like a charm! thanks, and so fast!
