### ISSUE TITLE
CCurlFile: HTTP returned error 403

### ISSUE THREAD

**Issue by Hir0-84** [rbuehlma/pvr.teleboy#5]
Dear developer,

I do not know if the issue is related to your PVR client or Teleboy block some ip addresses. Sometimes I cannot stream any channel and by looking at the log file I get the error message in the object.

By chance I discovered that the problem is linked to the ip address, if it starts with 46.xxx.xxx.xxx it does not work while it works well with 136.xxx.xxx.xxx. Have you ever experienced such a problem on your side?

Best regards,

**Comment by rbuehlma** [comment]
I'm not aware of such an issue but yes, Teleboy does block IPs based on the country. Maybe your IP has the wrong geo location. But without a full debug log, it probably not possible to help here.

**Comment by Hir0-84** [comment]
Thanks for replying. The IP is geolocated in Switzeland but maybe they also check the ISP. I take this opportunity to ask you if there is a way to activate both Zattoo and Teleboy having the possibility to choose either the provider going under TV or an automatic way to order the channels one after the other without mixing the channels of two provider together.

**Comment by rbuehlma** [comment]
You can run multiple PVR addons next to each other. This is a functionality of Kodi and not the PVR addon. From what I heard, this feature has some flaws but generally works. I my self do not use it.

**Comment by Hir0-84** [comment]
Dear rbuehlma,

I think there is a real issue, I cannot watch anything whatever ip I have on both Android TV and Linux OS. With the same ip I can watch the channels directly from teleboy website. Please find below a part of the log file:

[kodi.log](https://github.com/rbuehlma/pvr.teleboy/files/1497212/kodi.log)

**Comment by rbuehlma** [comment]
Its a bug probably in Kodi itself. It is also discussed (in german) here:
https://www.kodinerds.net/index.php/Thread/56619-PVR-Addon-f%C3%BCr-teleboy-ch/?postID=423598#post423598

**Comment by Hir0-84** [comment]
Ok I see, I'm using google translate :-). I tried to go back to the version that was working for me (nightly 20171107) but it does not work neither. Does the problem really come from kodi then? Can you now reproduce the bug or you need further tests from my side?

**Comment by rbuehlma** [comment]
It was a change by teleboy.ch but I have already implemented a workaround in the addon. The new addon should be available by tomorrow. The bug itself is in inputstream.adaptive.

**Comment by Hir0-84** [comment]
Ok thank you very much ;-)

**Comment by Hir0-84** [comment]
Sorry for disturbing you again. Have you transferred the latest fix on linux too? I did not get the update to v18.0.11 as for Android.

**Comment by rbuehlma** [comment]
Which build are you using? The current nightly should include also the current addon:
http://mirrors.kodi.tv/nightlies/android/

**Comment by Hir0-84** [comment]
On Android everything is fine. On Linux although I'm receiving every day the nightly updates for kodi the teleboy pvr client remains at the version 18.0.10. I have tried to update the package manually from synaptic but It does not find the latest version

**Comment by rbuehlma** [comment]
May be you have a manually installed (old) version of the addon. Try to uninstall the addon in Kodi and install it through the PPA (if not already don)

**Comment by Hir0-84** [comment]
Hi, I did the test you suggested but it did not work. I'm using the ppa http://ppa.launchpad.net/team-xbmc/xbmc-nightly/ubuntu and the only package I could see there is the version 18.0.10-1~artful. What linux distro do you use?

**Comment by rbuehlma** [comment]
Ah sorry, yes you are right, The PPA is updated on a non-regular basis. We could kindly ask @wsnipex if he could update the pvr.teleboy in the PPA? :)

**Comment by wsnipex** [comment]
done

**Comment by Hir0-84** [comment]
Thanks to both of you!
