### ISSUE TITLE
Channel name not according to label set label in recordings

### ISSUE THREAD

**Issue by tuxfuxch** [rbuehlma/pvr.teleboy#50]
Hi, 
if i get the recordings over json/rcp, i get the channel names according to the teleboy label, not the own chosen label in kodi.
can this be changed? would be greate. (not really important, but would be handy for my usecase)
thanks for considering in advance and have a nice time!
tuxfuxch

**Comment by rbuehlma** [comment]
The addon does neither provide you a feature to set channel names nor does it provide an json/rcp API. Both is implemented in Kodi itself. You should therefore open this ticket against Kodi. I do not know this api, but in my opinion, the channel name on the recording should be a technical reference to the channel and not the translated value. The translation should then be somewhere on the channel. Therefore, I do not expect this to be changed.
