### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by bendschs** [rbuehlma/pvr.teleboy#55]
getting the following error while trying to build pvr.teleboy from leia branch on debian buster.

```
/usr/include/c++/6/iosfwd:38:28: fatal error: bits/c++config.h: no such file or directory
 #include <bits/c++config.h>
```
i guess i am missing a library here?

**Comment by bendschs** [comment]
never mind, solved by reinstalling build-essential ...

**Comment by rbuehlma** [comment]
Thanks for the update. Closing the issue
