### ISSUE TITLE
Add of Nexus branch and related version

### ISSUE THREAD

**Issue by AlwinEsch** [rbuehlma/pvr.teleboy#66]
Since Kodi 20 Nexus has been available for a some months now, it is time to create an associated Nexus branch and release for all addons, for this then "20.0.0-Nexus".

I'm doing this at all addons where I have access, but you would have to make a change to this one.

**Comment by rbuehlma** [comment]
I have create a branch and hopefully did all the required changes. Could you confirm that:

https://github.com/rbuehlma/pvr.teleboy/commit/2190fc9c259d2d9cc50f1c267092d6f118cfb597

You now also have write access to this repo.

**Comment by AlwinEsch** [comment]
Also in the readme can changed then to "Nexus" by "[![Build Status]", thanks to make and also to give me rights.

Will create then also a request with minor other changes.

**Comment by AlwinEsch** [comment]
Can you look to github integrations here and on other addon about installed parts and Jenkins present:
![Bildschirmfoto vom 2021-09-17 00-02-00](https://user-images.githubusercontent.com/6879739/133691614-54a8895d-2a80-4625-b5d0-24de8dace846.png)

The Pull Requests are not reported to here and no build triggered: https://jenkins.kodi.tv/job/rbuehlma/job/pvr.zattoo/view/change-requests/

**Comment by rbuehlma** [comment]
I can't find any options to add such integrations. Is this something which is only available to organizations?

**Comment by rbuehlma** [comment]
Closing this ticket since "Jenkins - xbmc" does not seem to be publicly available.
