### ISSUE TITLE
Video issue on Live view

### ISSUE THREAD

**Issue by madsci** [rbuehlma/pvr.teleboy#7]
Hi rbuehlma

Great addon. It is indeed an excellent option to conventional TV broadcasters. The experience disturbs currently the issue with missing video in Live TV. When the time position is forwarded to the future (logically it jumps back to now), the video normally resumes without further blackouts.

In records or replay, the situation occurs singnificantly less.

Thank you for looking into this

Regards
Madsci/David

**Comment by madsci** [comment]
I use yor addon on Milhouse libreelec nightly builds with all you patches (Kodi 17, Intel x86_64)

**Comment by rbuehlma** [comment]
Hi David, thanks for the feedback. Its not exactly clear to me what the issue is. I never have missing video neither when starting a new stream nor when skipping backwards or forwards. When do these blackouts happen and how long/often are they? Do you use DASH or HLS stream (in the addons settings)?

**Comment by rbuehlma** [comment]
Oh, I just read that you are using Kodi 17. If possible, try to use Kodi 18, its a much better experience there from my point of view and no patches required anymore. Kodi 17 does not really support that addon.

**Comment by rbuehlma** [comment]
Ups, missed that it is about the Teleboy Addon. There only HLS streams are supported. I now switched to that addon and try to reproduce the issue. Do you have the "inputstream.adaptive" addon installed and activated? If not, could you do so? As far as I know, it handles the HLS streams better.

**Comment by madsci** [comment]
Yes, inputstream adaptive 2.2.14 is installed and activated

**Comment by madsci** [comment]
Without inputstream adaptive, a constant delay time of 5 s I S noticed, however, all channels show. With the is adaptive handler, either image comes immediately or never unless skipped.

**Comment by rbuehlma** [comment]
I do not have such an issue but the pvr.teleboy addon does only provide the URL to Kodi. The stream itself is then handled by Kodi itself or the inputstream.adaptive addon (if enabled). I therefore suggest to open the issue there. BTW: always provide a debug log as is most cases it won't be possible to help without.

**Comment by madsci** [comment]
I see. Thank you for your help. Backgrading inputstream adaptive to 2.1.13 still shows a random delay but video is played in most cases.

Therefore, I will adress the issue in this addon. I would like to provide debug logs, where do I find them?

D avid
