### ISSUE TITLE
Login Failed to Teleboy

### ISSUE THREAD

**Issue by MarkusGW** [rbuehlma/pvr.teleboy#72]
Im usisng the Kodi add on on a raspberry pi with Libreelec and since a week the Login with Teleboy is not working anymore.
I am using the RPi 3 LibreELEC-RPi2.arm-9.2.8.img.gz and installed the Teleboy Add On

**Comment by rbuehlma** [comment]
This has been fixed for the Addon Version 19.8.2 which is only available for Kodi 19. Since Kodi 19 is available for multiple months now, this will not be fixed for Kodi 18 anymore.
