### ISSUE TITLE
Support for Full-HD streams

### ISSUE THREAD

**Issue by jokay** [rbuehlma/pvr.teleboy#74]
It seems the plugin does not support Full-HD streams?

#### Environment

- Nvidia Shield TV Pro *(4K 60 Hz HDR10 Ready)*
- Kodi **19.3.0** *(3840 x 2160 @ 60.00 Hz)*
- Teleboy PVR client **19.8.2** *(Enable Dolby: true)*

#### Kodi app with plugin (only 720p)

![image](https://user-images.githubusercontent.com/18613935/147645960-62591bb8-9b1f-4026-8cb1-03c1633478a1.png)

#### Teleboy app (1080p)

![image](https://user-images.githubusercontent.com/18613935/147645993-4bf9ab43-a985-4ac4-ad54-3d0248eb76a7.png)

**Comment by rbuehlma** [comment]
I believe you are hitting a Bug in inputstream.adaptive:

Try to set the maximum bitrate in the settings of inputstream.adaptive to a heigh value like 99999999, try again and if it works, set it back to the original value. It should still work afterwards.

**Comment by jokay** [comment]
Yes, this works but it's a strange workaround :wink:
