### ISSUE TITLE
RTL not working

### ISSUE THREAD

**Issue by ROGERdotT** [rbuehlma/pvr.teleboy#77]
For three days now, the Teleboy plugin can no longer connect to RTL. Maybe something has been changed in the stream?
On the Teleboy website, the stream works perfectly..
![screenshot20220123033419](https://user-images.githubusercontent.com/35808625/150662491-55d0f44e-8eb4-451b-bedc-d34d12fb5657.png)
.

**Comment by rbuehlma** [comment]
Teleboy did enable DRM for RTL. You will need to make sure that the inputstream.adaptive addon is configured to play streams encrypted with widevine.

**Comment by ROGERdotT** [comment]
Thank you for the quick reply.
Unfortunately I am not a developer and maybe this is the wrong place for this problem.
But do I understand correctly that the developer of the addon actually has to change something?
Or can I do something myself?
In the addon settings I didn't find anything specific that I could change...

**Comment by rbuehlma** [comment]
The addon does already support it.

You need to activate widevine for inputstream.adaptive. Have a look at the https://kodi.wiki/view/Add-on:InputStream_Helper

**Comment by ROGERdotT** [comment]
Thank you very much, but the link doesn't help me.
It should work, but it doesn't. No idea how to activate widevine for inputstream.adaptive.
Well then, I'll just have to live with...
Sorry, I forgotto mention that I am on Windows 11 with Kodi 19.3.

**Comment by rbuehlma** [comment]
The link points to a Kodi addon. After installing that addon (it should be in the official repository), widevine and with it, RTL should work again.

**Comment by ROGERdotT** [comment]
Damn! I'm getting old.
Now it works. And sorry for the off-topic.
Thank you very much for your help 👍😎
I hadn't installed the plugin at all. I thought it was the plugin that is automatically installed when I install Playboy... 🙈

**Comment by rbuehlma** [comment]
I have now added that addon as a dependency. No manual installation will be required in the future :)

**Comment by ROGERdotT** [comment]
Oh, cool 😁
Then my confusion has led to something after all...😉
Have a great day.
