### ISSUE TITLE
2 Error while compiling... (GetAddonPath,GetBaseUserPath)

### ISSUE THREAD

**Issue by apprenticius** [rbuehlma/pvr.teleboy#78]
I just followed the 5 steps for compiling (build instructions):
------------------------------------------------------------------------------

-- Build files have been written to: ~/kodi_addons/pvr.teleboy/build/pvr.teleboy-prefix/src/pvr.teleboy-build
[ 82%] Performing forcebuild step for 'pvr.teleboy'
Force build of pvr.teleboy
[ 88%] Performing build step for 'pvr.teleboy'
Scanning dependencies of target sqlite
[  7%] Building C object lib/sqlite/CMakeFiles/sqlite.dir/sqlite3.c.o
[ 14%] Linking C static library libsqlite.a
[ 14%] Built target sqlite
Scanning dependencies of target pvr.teleboy
[ 21%] Building CXX object CMakeFiles/pvr.teleboy.dir/src/Utils.cpp.o
~/kodi_addons/pvr.teleboy/src/Utils.cpp: In static member function ‘static std::__cxx11::string Utils::GetFilePath(std::__cxx11::string, bool)’:
~/kodi_addons/pvr.teleboy/src/Utils.cpp:15:29: error: ‘GetAddonPath’ is not a member of ‘kodi’
   return (bUserPath ? kodi::GetAddonPath(strPath) : kodi::GetBaseUserPath(strPath));
                             ^~~~~~~~~~~~
~/kodi_addons/pvr.teleboy/src/Utils.cpp:15:29: note: suggested alternative:
In file included from ~/kodi_addons/pvr.teleboy/build/build/depends/include/kodi/Filesystem.h:11:0,
                 from ~/kodi_addons/pvr.teleboy/src/Utils.cpp:11:
~/kodi_addons/pvr.teleboy/build/build/depends/include/kodi/AddonBase.h:879:35: note:   ‘kodi::addon::GetAddonPath’
 inline std::string ATTR_DLL_LOCAL GetAddonPath(const std::string& append = "")
                                   ^~~~~~~~~~~~
~/kodi_addons/pvr.teleboy/src/Utils.cpp:15:59: error: ‘GetBaseUserPath’ is not a member of ‘kodi’
   return (bUserPath ? kodi::GetAddonPath(strPath) : kodi::GetBaseUserPath(strPath));
                                                           ^~~~~~~~~~~~~~~
CMakeFiles/pvr.teleboy.dir/build.make:62: recipe for target 'CMakeFiles/pvr.teleboy.dir/src/Utils.cpp.o' failed
make[6]: *** [CMakeFiles/pvr.teleboy.dir/src/Utils.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/pvr.teleboy.dir/all' failed
make[5]: *** [CMakeFiles/pvr.teleboy.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make[4]: *** [all] Error 2
CMakeFiles/pvr.teleboy.dir/build.make:112: recipe for target 'pvr.teleboy-prefix/src/pvr.teleboy-stamp/pvr.teleboy-build' failed
make[3]: *** [pvr.teleboy-prefix/src/pvr.teleboy-stamp/pvr.teleboy-build] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/pvr.teleboy.dir/all' failed
make[2]: *** [CMakeFiles/pvr.teleboy.dir/all] Error 2
CMakeFiles/Makefile2:180: recipe for target 'CMakeFiles/package-pvr.teleboy.dir/rule' failed
make[1]: *** [CMakeFiles/package-pvr.teleboy.dir/rule] Error 2
Makefile:157: recipe for target 'package-pvr.teleboy' failed
make: *** [package-pvr.teleboy] Error 2

**Comment by rbuehlma** [comment]
In case you are trying to build the Matrix branch, you will also need to checkout that Branch for Kodi. I will update the manual to reflect this.

**Comment by apprenticius** [comment]
Thanks a lot. Yes, the branch was the mistake.
