### ISSUE TITLE
Flickering playback

### ISSUE THREAD

**Issue by madsci** [rbuehlma/pvr.teleboy#8]
Hi rbuehlma

While testing your addon extensively, another issue came up. Sometimes the playback flickers like the frame rates of video and kodi do not match or if some frames are shown in wrong order.

Thanks
David

**Comment by rbuehlma** [comment]
The video stream is not handled by the pvr.teleboy addon but by https://github.com/peak3d/inputstream.adaptive

Also please retry with Kodi 18 as Kodi 17 is not supported with this addon.

**Comment by madsci** [comment]
Hi rbuehlma
Thank you for your reply. I use Kodi 18 Leia (Milhouse nigthly build 0407), Sorry for confusion, I have corrected my previous post.

Thank you for the hint. Playing with inputstream settings seemed to help.

David
