### ISSUE TITLE
Please branch from "Nexus" to "Omega"

### ISSUE THREAD

**Issue by phunkyfish** [rbuehlma/pvr.teleboy#80]
The build pipelines are setup, once you are done let me know and we can re-enable this add-on for Omega (Kodi 21) builds

**Comment by rbuehlma** [comment]
Branch created

**Comment by phunkyfish** [comment]
Request created: https://github.com/xbmc/repo-binary-addons/pull/156

**Comment by phunkyfish** [comment]
PR merged, thanks!
