### ISSUE TITLE
EPG unvollständig 

### ISSUE THREAD

**Issue by milan941899** [rbuehlma/pvr.teleboy#81]
Hallo,

gibt es eine Möglichkeit dass man im EPG zu jeder Sendung auch die entsprechende Beschreibung erhält?
Ist nur bei den wenigsten Sendern vorhanden.

Danke und LG

**Comment by rbuehlma** [comment]
Die Daten müssten sich befüllen, aber es dauert sehr lange. Ev. sogar mehrere Tage.

**Comment by rbuehlma** [comment]
Oh, nein, habe mich geirrt. Im Fall von Teleboy werden die Details tatsächlich nicht geladen. Durch die Art der API lässt sich dies leider nicht effizient machen.

**Comment by andreas-abel** [comment]
Was genau ist denn das Problem dabei? Unter tv.api.teleboy.ch/epg/broadcasts/<id> sind die entsprechenden Daten ja durchaus verfügbar. 

Wären hier zu viele Zugriffe nötig, was zu lange dauert bzw. nach einer bestimmten Anzahl von Teleboy blockiert wird? In diesem Fall könnte man sich ja immer noch auf die Hauptsender und -zeiten konzentrieren und wenigstens dort die Daten laden.

**Comment by rbuehlma** [comment]
Ja genau, das Problem ist, dass für jede Sendung ein Request nötig ist. Das würde viel zu viele Requests erzeugen, zu lange dauern und die Server von Teleboy zu stark belasten. Deshalb leider ein nogo.

Die Hauptsender wären wohl für alle wieder andere und müssten konfigurierbar gemacht werden. Das geht bei einem PVR addon nich so einfach und wäre auch dann nur eine Bastellösung.

Aus meiner Sicht lohnt sich der Aufwand dafür nicht. Falls es für jemand wichtig ist: Es handelt sich hier im OpenSource software ;)

**Comment by andreas-abel** [comment]
Vielen Dank für die Rückmeldung. Wurde schon einmal versucht, mit Teleboy Kontakt aufzunehmen, und zu fragen, ob das API entsprechend angepasst werden könnte?

Hauptsender wären für die meisten Nutzer des addons wohl Sender wie SRF1, SRF2, ARD, ZDF, usw. und das müsste nicht unbedingt konfigurierbar sein. Sicher gibt es Nutzer mit abweichenden Sehgewohnheiten, doch die dürften wohl in der Minderheit sein.

**Comment by rbuehlma** [comment]
> Wurde schon einmal versucht, mit Teleboy Kontakt aufzunehmen, und zu fragen, ob das API entsprechend angepasst werden könnte?

Vermutlich nicht und ich glaube auch nicht dass sie da Aufwand betreiben für dieses Addon.
