### ISSUE TITLE
Sender nur mit 720p?

### ISSUE THREAD

**Issue by saperlot** [rbuehlma/pvr.teleboy#90]
Tolle Arbeit erstens einmal!
Leider sind SRF1/2/info und ORF1 nur auf 720p. Die restlichen Privaten sind auf 1080.
Ist das ein Fehler oder ist das bewusst so?

**Comment by rbuehlma** [comment]
Das ist so bei Teleboy:

https://www.teleboy.ch/sender (siehe das kleine icon oben rechts beim Sender).

**Comment by saperlot** [comment]
Ah, danke
